name: Refresh Weather Data

on:
  schedule:
    - cron: '*/1 * * * *' # Runs automatically every 15 minutes
  workflow_dispatch: # Allows you to run it manually

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download latest weather XML
      run: curl -s https://xml.smg.gov.mo/c_actual_brief.xml -o weather.xml

    - name: Commit and Push if changed
      run: |
        git config --global user.name "weather-bot"
        git config --global user.email "actions@github.com"
        git add weather.xml
        git commit -m "Update live weather data" || exit 0
        git push
